import { ArrowUpRight, CheckCircle2, Clock3, Radio, TriangleAlert } from "lucide-react";
import Link from "next/link";
import { platformStats, tournaments } from "@/lib/demo-data";

export const metadata = { title: "Admin Dashboard" };

export default function AdminDashboard() {
  return <main className="admin-content"><div><div className="eyebrow">Tuesday, August 18</div><h1 className="admin-heading">Good afternoon, Waqas.</h1><p className="admin-subtitle">Here is what needs attention across eFightersArena.</p></div><section className="admin-stats">{platformStats.map((stat, index) => <div className="card admin-stat" key={stat.label}><div className="muted">{stat.label}</div><div className="stat-value">{stat.value}</div><div className={index === 2 ? "blue" : "green"}>{stat.delta}</div></div>)}</section><div className="dashboard-grid"><section className="card panel"><div className="section-header"><div><div className="eyebrow">Operations</div><h2 className="panel-title" style={{ marginTop: 7 }}>Active tournaments</h2></div><Link className="text-link" href="/admin/tournaments">Manage <ArrowUpRight size={14} /></Link></div><table className="data-table"><thead><tr><th>Tournament</th><th>Status</th><th>Entries</th><th>Next action</th></tr></thead><tbody>{tournaments.map((tournament) => <tr key={tournament.slug}><td><strong>{tournament.name}</strong><div className="muted">{tournament.game}</div></td><td><span className={`status ${tournament.status === "LIVE" ? "live" : ""}`}>{tournament.status}</span></td><td>{tournament.teams}</td><td className="green">Open control room</td></tr>)}</tbody></table></section><aside className="card panel"><h2 className="panel-title">Action centre</h2><div className="activity"><div className="activity-item"><TriangleAlert className="activity-dot" /><span><strong>3 result disputes</strong><br />Require operator review before advancement.</span></div><div className="activity-item"><Clock3 className="activity-dot" /><span><strong>18 identity reviews</strong><br />Gamers submitted new verification evidence.</span></div><div className="activity-item"><Radio className="activity-dot" /><span><strong>12 live matches</strong><br />All reporting feeds are healthy.</span></div><div className="activity-item"><CheckCircle2 className="activity-dot" /><span><strong>Daily backup verified</strong><br />Restore integrity check passed at 04:15.</span></div></div></aside></div></main>;
}
